export const CONSTANT = {
  WORDS_PER_PAGE_THRESHOLD: 30,
  TEXT_LENGTH_THRESHOLD: 300,
  HEADER_FROM_HEIGHT_PERCENTAGE: 0.02,
  FOOTER_FROM_HEIGHT_PERCENTAGE: 0.95,
  CMAP_URL: "./node_modules/pdfjs-dist/cmaps/",
  NORMALIZED_WIDTH: 3000,
  SCALE: 1,
};
